// Copyright (c) 2026 Tomi Poveda. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Logging/MessageLog.h"
#include "AssetGateValidationTypes.h"

/**
 * Provides diagnostic transport functionality for the AssetGate validation system.
 *
 * This class acts as a centralized mechanism for emitting, storing, and accessing
 * diagnostics related to asset validation. Diagnostics can either be emitted individually
 * or in batches and are forwarded to the Unreal Engine message log while also maintaining
 * an in-memory history for further operations.
 */
class ASSETGATECORE_API FAssetGateDiagnosticTransport
{
public:
	/** Return the singleton transport instance used by the validation pipeline. */
	static FAssetGateDiagnosticTransport& Get();

	/**
	 * Emit a single diagnostic to the central transport for processing.
	 *
	 * This method is responsible for forwarding the provided diagnostic to the editor message log,
	 * ensuring it appears in the appropriate Unreal Engine logging systems. It also stores the
	 * diagnostic in memory so it can be accessed via history-related operations like recent diagnostics
	 * retrieval.
	 *
	 * @param Diagnostic The diagnostic object to be emitted, containing details such as the associated
	 *        rule ID, asset path, severity, and a human-readable message.
	 */
	void Emit(const FAssetGateDiagnostic& Diagnostic);

	/**
	 * Emit a batch of diagnostics to the central transport for processing.
	 *
	 * This method forwards each diagnostic in the provided array to the editor message log,
	 * ensuring they appear in the appropriate Unreal Engine logging systems. It also stores
	 * the diagnostics in memory so they can be accessed via history-related operations like
	 * recent diagnostics retrieval.
	 *
	 * @param Diagnostics Array of diagnostic objects to be emitted. Each diagnostic includes
	 *        information such as the rule ID, asset path, severity, and a human-readable message.
	 */
	void EmitBatch(const TArray<FAssetGateDiagnostic>& Diagnostics);

	/**
	 * Retrieves a reference to the array containing the most recent diagnostics.
	 *
	 * This method provides access to an in-memory history of diagnostics emitted
	 * through the transport. The diagnostics stored in this array are limited
	 * by the configured maximum storage capacity to ensure efficient memory usage.
	 *
	 * @return A constant reference to the array of recent FAssetGateDiagnostic objects
	 *         retained by the transport for history-related operations.
	 */
	const TArray<FAssetGateDiagnostic>& GetRecentDiagnostics() const;

	/** Clear the recent diagnostics buffer for a new validation session. */
	void Clear();

	/**
	 * Configure the maximum number of diagnostics that can be stored in the system. Ensures
	 * older diagnostics are discarded when the specified limit is reached to maintain storage efficiency.
	 *
	 * @param InMaxStoredDiagnostics The maximum number of diagnostics to be stored.
	 */
	void SetMaxStoredDiagnostics(int32 InMaxStoredDiagnostics);

private:
	FAssetGateDiagnosticTransport();

	/**
	 * Convert an EAssetGateDiagnosticSeverity value to the corresponding EMessageSeverity::Type value.
	 *
	 * This utility function maps the severity levels defined in the AssetGate diagnostic system
	 * to the Unreal Engine message severity system, enabling consistent interpretation of
	 * diagnostic levels across the framework.
	 *
	 * @param InSeverity The diagnostic severity from the AssetGate system to be converted.
	 * @return The corresponding EMessageSeverity::Type that represents the same severity level.
	 */
	static EMessageSeverity::Type ToMessageSeverity(EAssetGateDiagnosticSeverity InSeverity);

	/**
	 * Emits a single diagnostic to the Unreal Engine message log.
	 *
	 * @param Diagnostic The diagnostic information to be logged, containing details
	 *        such as the rule ID, asset path, severity, and a human-readable message.
	 */
	static void EmitToMessageLog(const FAssetGateDiagnostic& Diagnostic);

	/**
	 * Stores a list of the most recent diagnostics generated by the AssetGate validation pipeline.
	 *
	 * This array is managed by the diagnostic transport system and holds an in-memory history of
	 * diagnostics for access during operations like troubleshooting or analyzing recent validation
	 * results. The storage capacity of this array is limited by the configured maximum, ensuring
	 * efficient memory usage by discarding the oldest diagnostics when the capacity is exceeded.
	 */
	TArray<FAssetGateDiagnostic> RecentDiagnostics;

	/**
	 * Define the maximum number of diagnostics that can be stored in memory by the diagnostic transport system.
	 *
	 * This value dictates the capacity of the internal storage buffer that retains recent diagnostics
	 * emitted through the system. Once the limit is reached, older diagnostics are discarded to
	 * maintain efficient memory usage. Adjusting this parameter can influence the amount of diagnostic
	 * history retained for operations such as troubleshooting or analysis.
	 */
	int32 MaxStoredDiagnostics{ 1024 };
};
