// Copyright (c) 2026 Tomi Poveda. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "UObject/Object.h"
#include "UObject/SoftObjectPath.h"
#include "AssetGateValidationTypes.generated.h"

/**
 * AssetGate severity level used to classify diagnostics independently of gate policy.
 */
UENUM(BlueprintType)
enum class EAssetGateDiagnosticSeverity : uint8
{
	Info,
	Warning,
	Error,
	Blocker
};

/**
 * Outcome semantics for one validator execution over one asset.
 * 
 * This maps to Unreal's data validation result model:
 *    - Valid: no relevant issues were found.
 *    - Invalid: at least one blocking issue was found.
 *    - NotValidated: validator could not or should not evaluate the asset.
 */
UENUM(BlueprintType)
enum class EAssetGateValidationOutcome : uint8
{
	Valid,
	Invalid,
	NotValidated,
};

/**
 * Stable diagnostic payload emitted by an AssetGate validator.
 */
USTRUCT(BlueprintType)
struct FAssetGateDiagnostic
{
	GENERATED_BODY()

	/** Stable identifier using RuleId:AssetPath[:PropertyPath] format. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AssetGate|Validation")
	FString Id;

	/** Rule identifier that produced this diagnostic. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AssetGate|Validation")
	FName RuleId{ NAME_None };

	/** Soft path of the asset being evaluated when the diagnostic was created. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AssetGate|Validation")
	FSoftObjectPath AssetPath;

	/** Optional property or sub-path context inside the asset. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AssetGate|Validation")
	FString PropertyPath;

	/** Human-readable diagnostic message suitable for editor output. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AssetGate|Validation")
	FText Message;

	/** Diagnostic severity independent of project gate thresholds. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AssetGate|Validation")
	EAssetGateDiagnosticSeverity Severity{ EAssetGateDiagnosticSeverity::Error };
};

/**
 * Aggregate result for one validator execution.
 */
USTRUCT(BlueprintType)
struct FAssetGateValidationResult
{
	GENERATED_BODY()

	/** Validation outcome aligned with Unreal data validation semantics. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AssetGate|Validation")
	EAssetGateValidationOutcome Outcome{ EAssetGateValidationOutcome::NotValidated };

	/** Structured diagnostics generated by the validator. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AssetGate|Validation")
	TArray<FAssetGateDiagnostic> Diagnostics;

	/**
	 * Add a diagnostic entry to the validation result. The diagnostic provides detailed information, such as the rule 
	 * that was evaluated, asset path context, and severity level.
	 *
	 * @param Diagnostic The diagnostic information to be added, including details like severity, message, 
	 *				     asset path, and rule identifier.
	 */
	void AddDiagnostic(const FAssetGateDiagnostic& Diagnostic);

	/**
	 * Check whether the validation result contains no diagnostics.
	 *
	 * @return True if there are no diagnostics in the validation result, false otherwise.
	 */
	bool IsEmpty() const;

	/**
	 * Create a validation result marked as valid with no associated diagnostics.
	 *
	 * @return A new FAssetGateValidationResult instance with the outcome set to Valid and an empty diagnostics array.
	 */
	static FAssetGateValidationResult MakeValid();

	/**
	 * Create a validation result marked as invalid, containing the provided diagnostics.
	 *
	 * @param InDiagnostics An array of diagnostics that provide detailed context for the invalidation,
	 *                    including severity levels, asset paths, rule identifiers, and messages.
	 * @return A new FAssetGateValidationResult instance with the outcome set to Invalid and the provided diagnostics.
	 */
	static FAssetGateValidationResult MakeInvalid(TArray<FAssetGateDiagnostic>&& InDiagnostics);

	/**
	 * Create a validation result marked as not validated, optionally including the provided diagnostics.
	 *
	 * @param InDiagnostics An optional array of diagnostics that provide additional context
	 *                      for the non-validation, including details like severity levels,
	 *                      asset paths, rule identifiers, and messages. Defaults to an empty array.
	 * @return A new FAssetGateValidationResult instance with the outcome set to NotValidated
	 *         and the provided diagnostics, if any.
	 */
	static FAssetGateValidationResult MakeNotValidated(TArray<FAssetGateDiagnostic>&& InDiagnostics = {});
};

/**
 * Utility methods for generating stable validation identifiers.
 */
struct FAssetGateValidationId
{
	/**
	 * Generates a unique diagnostic identifier for asset validation purposes.
	 *
	 * @param RuleId The identifier of the validation rule being applied.
	 * @param AssetPath The path to the asset being validated.
	 * @param PropertyPath Optional. The path to the specific property of the asset being analyzed.
	 * @return A string representing the generated diagnostic identifier.
	 */
	static FString MakeDiagnosticId(
		const FName RuleId,
		const FSoftObjectPath& AssetPath,
		const FString& PropertyPath = FString());
};
